# Generated by Django 3.0.4 on 2020-04-26 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200424_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='is_favorite',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Category'),
        ),
    ]
